### ISSUE TITLE
Multiple colors in same string

### ISSUE THREAD

**Issue by Milerius** [qqtop/NimCx#2]
![image](https://user-images.githubusercontent.com/21139416/57718043-bff46d00-767c-11e9-8fba-2cada3276b31.png)

Hello, i'm using your library now, i want to know how you mix multiple color in the same line ?

for the line:
`config create <name> (create a config with the given name)`

**Comment by qqtop** [comment]
Currently you can do following for your help block:
```
import nimcx

println("Usage:")
printLnBiCol("help (show this message)",colLeft = yellow,colRight = termwhite,sep = " ",xpos =  7)
printLnBiCol("exit (quitting the app)",colLeft = yellow,colRight = termwhite,sep = " ",xpos = 7)
printLnBiCol("clear (clearing the screen)",colLeft = yellow,colRight = termwhite,sep = " ",xpos = 7)
printBiCol("config create",colLeft = yellow,colRight = dodgerBlue,sep = " ",xpos = 7)
printHL("<name>",substr = "name",col = magenta)
printLn(" (create a config with the given name)")
decho(2)
```

Your config create line has 5 color changes -> yellow,blue,white,magenta,white
for simple usage as per your example you can also do

```

echo(yellow,"config ",dodgerBlue,"create ",termwhite,"<",magenta,"name",termwhite,"> (create a config with the given name)")
```

**Comment by Milerius** [comment]
Thank's a lot my friend

**Comment by Milerius** [comment]
@qqtop 

How we set default background for `printLnBiCol` function ?

by default it's seem's to be black it's weird :'( 

![image](https://user-images.githubusercontent.com/21139416/57877254-a6d3f380-7817-11e9-9d51-b28c96f3387e.png)

**Comment by qqtop** [comment]
Please reinstall via

```
nimble install nimcx

```
the background has been set to bgDefault 

Hope it helps for your use case and terminal.

The best terminal prog to use is Konsole from the KDE distributions  ,
available for Debian/Ubuntu via apt or synaptic.

Custom terminals in editors like VCS etc may be hit or miss , also funny color setups
in terminal profiles may give unexpected results.

**Comment by Milerius** [comment]
Thank's a lot
