### ISSUE TITLE
sys/ioctl.h: No such file or directory

### ISSUE THREAD

**Issue by cup** [qqtop/NimCx#3]
Using this file:

~~~nim
import nimcx
~~~

I get this result:

~~~
$ nim compile \
> --gcc.exe:x86_64-w64-mingw32-gcc \
> --gcc.linkerexe:x86_64-w64-mingw32-gcc \
> aa.nim
[...]
C:\Users\Steven\nimcache\aa_d\
_7_7C87Users7Steven7.nimble7pkgs7nimcx-1.0.07nimcx7cxglobal.nim.c:11:10: fatal
error: sys/ioctl.h: No such file or directory
~~~

**Comment by qqtop** [comment]
Sorry  , cannot comment on anything windows , I left the windows world in 1998.

**Comment by cup** [comment]
I might be able to do a patch if thats acceptable

**Comment by qqtop** [comment]
I think the best way is to fork the repo , then you can adjust  or  remove linux/posix related code as per your requirement. It has a MIT license .

**Comment by cup** [comment]
I think better option is to have one repo that is portable - I will try to write a patch if you are open to it

**Comment by qqtop** [comment]
Someone has done this before for and got it running on windows7 some years ago,
but everything has evolved and very much changed since.
I think he just cloned the repo  and removed unwanted bits and pieces  until it worked .
The first thing to look for is Linux system calls , which can mostly be found via search for execCmd . 
I agree that portable is the best option , if everything works for both Os I am open to it.

**Comment by cup** [comment]
@qqtop I had a chance to look at this more closely. It seems the errors are a
result of function `getTerminalWidth`:

https://github.com/qqtop/NimCx/blob/12be4fd9d33c93d491c9ee1c3cd248d839919649/nimcx/cxglobal.nim#L159

and `getTerminalHeight`:

https://github.com/qqtop/NimCx/blob/12be4fd9d33c93d491c9ee1c3cd248d839919649/nimcx/cxglobal.nim#L179

However I am confused why these are needed, as it seems `getTerminalWidth` is
already provided by Nim itself for Linux [1] and Windows [2]. Also and
`getTerminalHeight` is provided for Linux [3] and Windows [4]. I can still write
a patch if need be, but couldnt we just change to use the internal functions,
as this appears to be a solved problem?

[1] https://github.com/nim-lang/Nim/blob/f50e4500/lib/pure/terminal.nim#L240
[2] https://github.com/nim-lang/Nim/blob/f50e4500/lib/pure/terminal.nim#L127
[3] https://github.com/nim-lang/Nim/blob/f50e4500/lib/pure/terminal.nim#L257
[4] https://github.com/nim-lang/Nim/blob/f50e4500/lib/pure/terminal.nim#L135

**Comment by qqtop** [comment]
I pushed an update and removed those . 
Nim is evolving fast now and I am sure some other functions or procs
in nimcx can be further improved or even eliminated.

**Comment by cup** [comment]
@qqtop thanks, that fixed the issue! However something else is happening now.
With this file:

~~~nim
echo 11
~~~

I get this output:

~~~sh
$ ./aa
11
~~~

but with this file:

~~~nim
import nimcx
echo 11
~~~

I get this output:

~~~
$ ./aa


11
~~~

I can open a new issue if you want.

**Comment by qqtop** [comment]
It's been fixed now .

**Comment by cup** [comment]
@qqtop thank you! looks good!

I will close this now, hopefully no further issues

thanks again
