### ISSUE TITLE
Leading zero

### ISSUE THREAD

**Issue by cup** [qqtop/NimCx#4]
NimCx can add trailing zero, remove digits and add thousands separator:

~~~nim
import nimcx
const aa = 1234.56
echo ff2(aa, 3)
echo ff2(aa, 1)
echo ff2(aa, 0)
~~~

However it seems to have no way to add leading zero. Compare with other options:

~~~nim
import strformat
const aa = 1234.56
echo &"{aa:08}"
~~~

~~~nim
import strfmt
const aa = 1234.56
echo "{:08}".fmt(aa)
~~~

- https://github.com/kaushalmodi/strfmt
- https://nim-lang.github.io/Nim/strformat

**Comment by qqtop** [comment]
Maybe this helps a bit :
```
# pad a numberstring with 0 on the left until overall width is 15 and show 5 after comma positions
echo cxlpad(ff2(1234.56,5),15,"0")
```

**Comment by cup** [comment]
@qqtop it seems like `cxlpad` is a string method, while my other examples are number methods. so your solution works but its not ideal as it requires 2 function calls. I think I will use the other methods I listed for now

thank you

**Comment by cup** [comment]
With this file:

~~~nim
import nimcx
let aa = ff2(-1, 0)
echo cxlpad(aa, 3, "0")
~~~

Result:

~~~
0-1
~~~

With this file:

~~~nim
import strformat
let aa = -1
echo &"{aa:03}"
~~~

Result:

~~~
-01
~~~

**Comment by qqtop** [comment]
Fixed this .. I hope.
You are finding all the edge cases . Thank's for looking.

Use the new function cxlpadN
```
echo cxlpadN(ff2(-1, 0), 8, "0")

```
gives here:

```
-0000001
```

**Comment by cup** [comment]
@qqtop yes that you, that does produce expected output

however I think some method should be available that accepts number input. this
is available with base Nim:

~~~nim
import strformat
const aa = 11
echo &"{aa:03}"
~~~

as well as other languages like C:

~~~c
#include <stdio.h>
int main() {
   printf("%03d\n", 11);
}
~~~

Python:

~~~py
format(11, '03')
~~~

JavaScript:

~~~js
(11).toLocaleString(0, {minimumIntegerDigits: 3});
~~~

PHP:

~~~php
printf('%03d\n', 11);
~~~

Go:

~~~go
package main
import "fmt"
func main() {
   fmt.Printf("%03d\n", 11)
}
~~~

D:

~~~d
import std.format, std.stdio;
void main() {
   auto aa = "%03d".format(11);
   writeln(aa);
}
~~~

**Comment by qqtop** [comment]
It is available since now.

```
import nimcx

echo cxLpadN(ff2(1234.45,5),15,"0")
echo cxLpadN(1234.45,15,"0")
echo cxLpadN(-1.45, 15)

# obviously stdlib functions are available in Nimcx too
assert cxLpadN(-1.45, 6)  ==  &"{-1.45:06}"   

# you even can let python do the formating
# via import nimpy or run awk via execCmdEx  
# at least under Linux

```
Nimcx was conceived before strfmt was a thing.

**Comment by cup** [comment]
@qqtop this file:

~~~nim
import nimcx
echo cxLpadN(-1, 3)
~~~

makes this:

~~~
-01
~~~

Perfect! However this file:

~~~nim
import nimcx
let aa = ff2(1234, 0)
echo cxLpadN(aa, 8)
~~~

makes this:

~~~
0001,234
~~~

which some would say is not correct. However given the circumstances I think its
reasonable to expect that result, as `cxLpadN` isnt currently programmed to add
the extra separators needed to create a correct result. Here is JavaScript with
correct output:

~~~js
(1234).toLocaleString(0, {minimumIntegerDigits: 7});
"0,001,234"
~~~

Python:

~~~py
>>> format(1234, '08,')
'0,001,234'
~~~

Go:

~~~go
package main
import "golang.org/x/text/language"
import "golang.org/x/text/message"
func main() {
   message.NewPrinter(language.English).Printf("%07d\n", 1234)
   // 0,001,234
}
~~~

Interestingly D, fails in similar fashion:

~~~d
import std.format, std.stdio;
void main() {
   auto aa = "%09,d".format(1234);
   writeln(aa);
   // 00001,234
}
~~~

I am not sure what would be a good way to fix this problem. If you try this:

~~~nim
ff2(0001234)
~~~

the leading zeros just get stripped, and `ff2` does not currently support string
input. I can understand I you do not want to fix this, or even if you think
the current output is correct, but I felt it proper to report it. Also I will
be reporting the D issue as well, thanks again!

**Comment by qqtop** [comment]
You are getting into the rabbit hole of custom formating.
It depends on what you want to achieve .

Try this  

```
import nimcx
let aa = 1234
echo insertsep(cxLpadN(aa,7),',',3).multiReplace((",,",","))
```
you get

```
0,001,234
```

which basically means nothing to most library users unless they need some custom table alignment,
besides that you might still have to consider US or Eu locale . So ...  lets close this.

**Comment by cup** [comment]
@qqtop you were right about rabbit hole, all is good now.

thanks for the patches!
