### ISSUE TITLE
Does NimCX require nim v1.9.1?  Latest stable is 1.6.10

### ISSUE THREAD

**Issue by bob-u** [qqtop/NimCx#5]
![image](https://user-images.githubusercontent.com/61708771/215363667-0ef53809-5402-46b5-bfef-43d79744ff21.png)

**Comment by qqtop** [comment]
The nimble file has now been updated so you can try to install .
The library is usually test compiled  against latest devel , but it also works for stable version.
It compiled on Debian based systems (Ubuntu,Parrot,Zorin) and also on a recent openSUSE Tumbleweed.

**Comment by bob-u** [comment]
Thank you!
